SELECT
    u.USER_ID, u.USERNAME, t.TRAINING_ID, t.TRAINING_DATE, COUNT(t.USER_ID) AS COUNT
FROM
    USERS u, TRAINING_DETAILS t
WHERE
        u.USER_ID = t.USER_ID
GROUP BY u.USER_ID, u.USERNAME, t.TRAINING_ID, t.TRAINING_DATE
HAVING COUNT(t.TRAINING_ID) > 1
ORDER BY t.TRAINING_DATE DESC, t.TRAINING_ID;